<?php

namespace Proxies\__CG__\Wayci\BackendBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Pais extends \Wayci\BackendBundle\Entity\Pais implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function __toString()
    {
        $this->__load();
        return parent::__toString();
    }

    public function setNombre($nombre)
    {
        $this->__load();
        return parent::setNombre($nombre);
    }

    public function getNombre()
    {
        $this->__load();
        return parent::getNombre();
    }

    public function setCodigo($codigo)
    {
        $this->__load();
        return parent::setCodigo($codigo);
    }

    public function getCodigo()
    {
        $this->__load();
        return parent::getCodigo();
    }

    public function setIdentificador($identificador)
    {
        $this->__load();
        return parent::setIdentificador($identificador);
    }

    public function getIdentificador()
    {
        $this->__load();
        return parent::getIdentificador();
    }

    public function addSubcategoria(\Wayci\BackendBundle\Entity\Subcategoria $subcategorias)
    {
        $this->__load();
        return parent::addSubcategoria($subcategorias);
    }

    public function removeSubcategoria(\Wayci\BackendBundle\Entity\Subcategoria $subcategorias)
    {
        $this->__load();
        return parent::removeSubcategoria($subcategorias);
    }

    public function getSubcategorias()
    {
        $this->__load();
        return parent::getSubcategorias();
    }

    public function addProducto(\Wayci\BackendBundle\Entity\Producto $productos)
    {
        $this->__load();
        return parent::addProducto($productos);
    }

    public function removeProducto(\Wayci\BackendBundle\Entity\Producto $productos)
    {
        $this->__load();
        return parent::removeProducto($productos);
    }

    public function getProductos()
    {
        $this->__load();
        return parent::getProductos();
    }

    public function addMoneda(\Wayci\BackendBundle\Entity\Moneda $monedas)
    {
        $this->__load();
        return parent::addMoneda($monedas);
    }

    public function removeMoneda(\Wayci\BackendBundle\Entity\Moneda $monedas)
    {
        $this->__load();
        return parent::removeMoneda($monedas);
    }

    public function getMonedas()
    {
        $this->__load();
        return parent::getMonedas();
    }

    public function addTipocuenta(\Wayci\BackendBundle\Entity\Tipocta $tipocuentas)
    {
        $this->__load();
        return parent::addTipocuenta($tipocuentas);
    }

    public function removeTipocuenta(\Wayci\BackendBundle\Entity\Tipocta $tipocuentas)
    {
        $this->__load();
        return parent::removeTipocuenta($tipocuentas);
    }

    public function getTipocuentas()
    {
        $this->__load();
        return parent::getTipocuentas();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'nombre', 'codigo', 'identificador', 'subcategorias', 'productos', 'monedas', 'tipocuentas');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}