parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: r7000326_ecoin
    database_user: r7000326_user
    database_password: Lavalle662
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: 9e32e5efcb231fde4900709a1972836aa2ba106b
    database_path: null
