Wayci\BackendBundle\Entity\Via:
    type: entity
    table: via
    repositoryClass: Wayci\BackendBundle\Entity\ViaRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        descripcion:
            type: string
            length: '50'
    lifecycleCallbacks: {  }
